### ISSUE TITLE
suggestion: concat * lines into one

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/gui#5]
What would it take to parse the subsequent asterisked lines into one (obvisously keep `* [something` as new lines)

e.g. this
![example](https://user-images.githubusercontent.com/16656956/174461328-5ca3d846-61b1-4f1f-924e-dd2666d703db.png)

becomes this
![result](https://user-images.githubusercontent.com/16656956/174461432-24a7081b-3ae9-41bb-b021-81f5e80549c0.png)

**Comment by icpantsparti2** [comment]
Closing this issue, and adding to the ToDo (issue #1).

When I had a quick look at this some time ago I did not easily figure it out (my concat attempts broke layout either side).
