### ISSUE TITLE
suggestion - allowed to edit value and exported as user-overrides.js

### ISSUE THREAD

**Issue by braboobssiere** [arkenfox/gui#6]
topic

**Comment by icpantsparti2** [comment]
Not sure that I will get around to bringing this to the gui here.

I have played with this type of feature on my own repo.  You can try my github pages website [userjs-tool.html](https://icpantsparti2.github.io/firefox-user.js-tool/userjs-tool.html), use the buttons `[Load arkenfox]` and `[Collect]`, this allows you to click/edit values and shows the changes at the top.
