### ISSUE TITLE
Old arkenfox versions

### ISSUE THREAD

**Issue by g-2-s** [arkenfox/gui#7]
Hi, can this gui tool also list old arkenfox iterations? I'm using FF ESR with arkenfox user.js version 115-1 and it honestly would be nice if this tool could display it as well as the latest and greatest.

**Comment by icpantsparti2** [comment]
Hi.  I have just made this possible, and added to [FAQ](https://github.com/arkenfox/gui).

For example, to see arkenfox version 115.1 you would use:  
[https://arkenfox.github.io/gui/?v=115.1](https://arkenfox.github.io/gui/?v=115.1)

**Comment by Thorin-Oakenpants** [comment]
was hoping to save myself some work

![damnit](https://github.com/arkenfox/gui/assets/16656956/ba86e447-e683-49e9-847f-e5695d8f1d86)
